# fly.toml app configuration file generated for noebs on 2023-10-12T18:09:33+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "noebs"
primary_region = "ams"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
